Please have the product_data.txt in the same location as the .py for it to run properly 
